-- AlterTable: Add ACTIVE to orders status enum
ALTER TABLE `orders` MODIFY COLUMN `status` ENUM('AWAITING_PAYMENT', 'PENDING', 'CONFIRMED', 'ACTIVE', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED') NOT NULL DEFAULT 'AWAITING_PAYMENT';
